# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DeckConnect
masthead_title: DeckConnect
url: "https://deckconnect.me"
logo: "/assets/images/88x88.png"
og_image: "/assets/images/120x120.png"
subtitle: "Connect Unreal & Elgato together~!"
description: >- # this means to ignore newlines until "baseurl:"
  DeckConnect empowers your workflow with the Unreal Engine using
  an Elgato Stream Deck. Connect the two together and control your 
  Unreal Application or Editor directly from your device!
github_username: SocksTheWolf
locale: "en-US"
minimal_mistakes_skin: dark
search: true
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
enable_copy_code_button: true
atom_feed:
  hide: true
lunr:
  search_within_pages: true

# Site settings
show_downloads: false
price: "TBA"

# Outputting
permalink: pretty
pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

include:
  - _pages
  - favicon.ico

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site
  - _drafts
  - .vscode
  - CNAME

# Plugins (previously gems:)
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll_img
  - jekyll-liquify

img:
  die_on_img_error: false
  pry_on_img_error: false

jekyll_compose:
  default_front_matter:
    posts:
      layout: single
      author_sidebar: false
      description: An Update Post Regarding DeckConnect
      categories:
        - Updates
      tags:
        - Unreal
        - Elgato

author:
  name   : "SocksTheWolf"
  avatar : "/assets/images/128x128.png"
  bio    : "DeckConnect Developer"
  github : "SocksTheWolf"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://socksthewolf.com"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://twitch.tv/socksthewolf"

footer:
  links:
    - label: "Developer Website"
      icon: "fa fa-fw fa-earth-americas"
      url: "https://socksthewolf.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/socksthewolf"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://twitch.tv/socksthewolf"
    - label: "Contact"
      icon: "fa fa-fw fa-envelope"
      url: "/contact"

defaults:
  - scope:
      path: ""
      type: pages
    values: 
      layout: single
      author_profile: false
      read_time: false
      related: false
      share: false
  # updates
  - scope:
      path: "updates/_posts"
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      comments: false
      categories:
        - updates
      share: true
      related: false
      toc: false
  # tips
  - scope:
      path: "tips/_posts"
      type: posts
    values:
      layout: single
      author_profile: false
      categories:
        - tips
      read_time: false
      show_date: true
      comments: false
      share: true
      related: false
      toc: false
  # examples
  - scope:
      path: "examples/_posts"
      type: posts
    values:
      layout: single
      author_profile: false
      categories:
        - examples
      read_time: false
      show_date: true
      comments: false
      share: true
      related: false
  # posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      show_date: true
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
