# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DeckConnect
masthead_title: DeckConnect
logo: "/assets/images/88x88.png"
url: "https://deckconnect.me"
og_image: "/assets/images/120x120.png"
subtitle: "Connect Unreal & Elgato together~!"
description: >- # this means to ignore newlines until "baseurl:"
  DeckConnect is a set of plugins for the Elgato Stream Deck and
  the Unreal Engine. Connect the two together and control your 
  Unreal Application or Editor directly from your device!
github_username: SocksTheWolf
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
paginate: 5
paginate_path: "/updates/:num/"
permalink: pretty
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - favicon.ico

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll_img

img:
  die_on_img_error: true
  pry_on_img_error: false

author:
  name   : "SocksTheWolf"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  github : "SocksTheWolf"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Developer Home"
      icon: "fa fa-fw fa-earth-americas"
      url: "https://socksthewolf.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/socksthewolf"
    - label: "Contact"
      icon: "fa fa-fw fa-envelope"
      url: "/contact"

defaults:
  - scope:
      path: ""
      type: pages
    values: 
      layout: single
      author_profile: false
      read_time: false
      related: false
      share: false
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
